FROM ubuntu:focal

RUN apt-get update
RUN apt install \
    unzip \
    debootstrap \  
    binfmt-support dosfstools libsystemd-dev libsodium-dev \
    qemu-utils qemu-efi-aarch64 qemu-system-arm qemu-user-static \
    -y

RUN mkdir /work

WORKDIR /work